### ISSUE TITLE
Custom colors do not work

### ISSUE THREAD

**Issue by Yiuman** [mrinalini-m/vue-threejs-birds#1]
at source code lines :221
const color1 =
            !this.color1 && this.color1 !== 0 ? 0x8bf329 : this.color1,
          color2 = !this.color2 && this.color1 !== 0 ? 0x298bf3 : this.color2,

**Comment by mrinalini-m** [comment]
I fixed the issue with this [commit](https://github.com/mrinalini-m/vue-threejs-birds/commit/949146ac0355a77b38cf115f8c00326d8c8bda4f). It seems to be working for me. 

But I refactored to just add the defaults to the props: `color1: { default: 0x8bf329, type: [String, Number], required: false }`.

**Comment by Yiuman** [comment]
Thanks. Now it works
